# Generated by Django 3.1.7 on 2021-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Freaking Awesome Blog', max_length=255),
        ),
    ]
