# Generated by Django 3.1.7 on 2021-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialblog', '0006_auto_20210506_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='no snippet', max_length=255),
        ),
    ]
